### ISSUE TITLE
[REVIEW]: OrpailleCC: a Library for Data Stream Analysis on Embedded Systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1485]
**Submitting author:** @Azazel7 (<a href="http://orcid.org/0000-0003-2129-5517">Martin Khannouz</a>)
**Repository:** <a href="https://github.com/big-data-lab-team/OrpailleCC" target ="_blank">https://github.com/big-data-lab-team/OrpailleCC</a>
**Version:** 1.0
**Editor:** @gkthiruvathukal
**Reviewer:** @sepandhaghighi
**Archive:** <a href="https://doi.org/10.5281/zenodo.3266109" target="_blank">10.5281/zenodo.3266109</a>

## Status

[![status](http://joss.theoj.org/papers/31cdf3b454ba6828d47bf0cdcfcad7ca/status.svg)](http://joss.theoj.org/papers/31cdf3b454ba6828d47bf0cdcfcad7ca)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/31cdf3b454ba6828d47bf0cdcfcad7ca"><img src="http://joss.theoj.org/papers/31cdf3b454ba6828d47bf0cdcfcad7ca/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/31cdf3b454ba6828d47bf0cdcfcad7ca/status.svg)](http://joss.theoj.org/papers/31cdf3b454ba6828d47bf0cdcfcad7ca)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/big-data-lab-team/OrpailleCC" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sepandhaghighi, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @gkthiruvathukal know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/big-data-lab-team/OrpailleCC">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0
- [x] **Authorship:** Has the submitting author (@Azazel7) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sepandhaghighi it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by sepandhaghighi** [comment]
review in progress, would say "accept with minor revisions".
added 6 issues, after those are closed, this should be ready to accept
big-data-lab-team/OrpailleCC/issues/5
big-data-lab-team/OrpailleCC/issues/6
big-data-lab-team/OrpailleCC/issues/7
big-data-lab-team/OrpailleCC/issues/8
big-data-lab-team/OrpailleCC/issues/9
big-data-lab-team/OrpailleCC/issues/10

**Comment by sepandhaghighi** [comment]
another minor issue ;-)
big-data-lab-team/OrpailleCC/issues/11

**Comment by gkthiruvathukal** [comment]
@azazel7 Please see the issues raised by @sepandhaghighi.

**Comment by azazel7** [comment]
All issues should be fixed now.

**Comment by sepandhaghighi** [comment]
> All issues should be fixed now.

Nice work, but some minor issues remained!

1. Please take another look at [this issue](https://github.com/big-data-lab-team/OrpailleCC/issues/6)
2. Missing DOIs
3. Solve paper compilation problem

**Comment by azazel7** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by azazel7** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.14778/2824032.2824132 is OK
- 10.1109/lcn.2004.72 is OK
- 10.1109/bigdata.2018.8621946 is OK
- 10.1145/2674005.2674994 is OK
- 10.1016/j.future.2017.03.026 is OK
- 10.1145/3147.3165 is OK
- 10.1145/362686.362692 is OK
- 10.3390/a10030080 is OK
- 10.2307/2685209 is OK
- 10.1109/hicss.2000.926982 is OK
- 10.1109/glocom.2002.1188034 is OK
- 10.1109/35.925682 is OK
- 10.1145/1656274.1656278 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
If I understand correctly, the file `paper.yml` is missing. However, there is no mention of such a file in the author guideline nor in the documentation at joss.readthedocs.io. I have checked the repositories of already published papers, but I couldn't find any example of a paper.yml.

**Comment by danielskatz** [comment]
paper.yml is internally created - you do not have to create this. Perhaps this was a whedon hiccup, which we can check by trying again, or perhaps there is something wrong in your md or bib file that is leading to a problem with an error message that is not helpful

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
If there's an error, it's not obvious to me. You could undo your most recent changes and try again, to see if this is a whedon error or one related to your changes. I see that you added spaces at the start of lines 18 and 19, which might be confusing whedon.

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf from branch debug_whedon

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:149:in `parse_affiliations': undefined method `each' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:135:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:84:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:149:in `parse_affiliations': undefined method `each' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:135:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:84:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:149:in `parse_affiliations': undefined method `each' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:135:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:84:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: keywords, affiliations, date (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: keywords (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'float.sty' from line
  '! LaTeX Error: File `float.sty' not found.'
Latexmk: Missing input file: 'float.sty' from line
  '! LaTeX Error: File `float.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1485/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:93:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1485 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'float.sty' from line
  '! LaTeX Error: File `float.sty' not found.'
Latexmk: Missing input file: 'float.sty' from line
  '! LaTeX Error: File `float.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by sepandhaghighi** [comment]
@azazel7 
I suggest you, remove `paper.yml`, `paper.tex` and `Makefile` and work in wizard mode (only `paper.md` and `paper.bib`)

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by sepandhaghighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01485/joss.01485/10.21105.joss.01485.pdf)

**Comment by sepandhaghighi** [comment]
@azazel7 Now add your references to `paper.md`

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01485/joss.01485/10.21105.joss.01485.pdf)

**Comment by sepandhaghighi** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.14778/2824032.2824132 is OK
- 10.1109/lcn.2004.72 is OK
- 10.1109/bigdata.2018.8621946 is OK
- 10.1145/2674005.2674994 is OK
- 10.1016/j.future.2017.03.026 is OK
- 10.1145/3147.3165 is OK
- 10.1145/362686.362692 is OK
- 10.3390/a10030080 is OK
- 10.2307/2685209 is OK
- 10.1109/hicss.2000.926982 is OK
- 10.1109/glocom.2002.1188034 is OK
- 10.1109/35.925682 is OK
- 10.1145/1656274.1656278 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by sepandhaghighi** [comment]
@azazel7 Thanks for your efforts ;-)
@gkthiruvathukal Looks good to me

**Comment by gkthiruvathukal** [comment]
@sepandhaghighi Many thanks for your excellent and thorough review efforts!

@azazel7  I have gone through the checklist, and I'm ready to accept.
Can you please archive the accepted version of the package and provide an associated DOI (e.g., via Zenodo)?

**Comment by azazel7** [comment]
@gkthiruvathukal If I am not mistaken, the DOI is 10.5281/zenodo.3266109. The last release (1.0.0.1) is just for the paper modifications. The corresponding webpage is [there](https://zenodo.org/record/3266109).

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by gkthiruvathukal** [comment]
@whedon set 10.5281/zenodo.3266109 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3266109" target="_blank">10.5281/zenodo.3266109</a> is the archive.

**Comment by sepandhaghighi** [comment]
@gkthiruvathukal 
Hi
Just a friendly reminder. 
I think you forgot this paper, its ready to be accepted by you.

Best Regards
Sepand Haghighi

**Comment by gkthiruvathukal** [comment]
@sepandhaghighi Thanks for the reminder.

So here is the final checklist for @azazel7 to fill in. Can you please do the following? (This is something I am doing for all submissions now, so you can just check the ones you already did above.)

- [ ] Make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] List the Zenodo DOI of the archived version here.

Once these are done, I will do a final proofread and signal the JOSS EICs to process acceptance.

**Comment by azazel7** [comment]
@gkthiruvathukal 

- [x] The tag release is [here](https://github.com/big-data-lab-team/OrpailleCC/releases).
- [x] The Zenodo archive is available [there](https://zenodo.org/record/3266109).
- [x] The metadata has been updated (author list with ORCID, the title of the release). 
- [x] There is only one Zenodo DOI and it is 10.5281/zenodo.3266109.

**Comment by gkthiruvathukal** [comment]
@whedon set archive 10.5281/zenodo.3266109

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by gkthiruvathukal** [comment]
@whedon set 10.5281/zenodo.3266109 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3266109" target="_blank">10.5281/zenodo.3266109</a> is the archive.

**Comment by gkthiruvathukal** [comment]
@whedon set 1.0 as version

**Comment by whedon** [comment]
OK. 1.0 is the version.

**Comment by gkthiruvathukal** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01485/joss.01485/10.21105.joss.01485.pdf)

**Comment by gkthiruvathukal** [comment]
@openjournals/joss-editors  I recommend that we proceed with accepting this submission.

**Comment by kyleniemeyer** [comment]
Hi @azazel7, could you please merge the two small PRs I just submitted, which make a few edits to your paper? https://github.com/big-data-lab-team/OrpailleCC/pull/15 and https://github.com/big-data-lab-team/OrpailleCC/pull/16

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01485/joss.01485/10.21105.joss.01485.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/863

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/863, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1154486445261746176) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/864
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01485](https://doi.org/10.21105/joss.01485)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @azazel7 on your paper's publication in JOSS! Thanks to @sepandhaghighi for reviewing and @gkthiruvathukal for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01485/status.svg)](https://doi.org/10.21105/joss.01485)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01485">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01485/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01485/status.svg
   :target: https://doi.org/10.21105/joss.01485
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01485/status.svg)](https://doi.org/10.21105/joss.01485)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
