### ISSUE TITLE
[PRE REVIEW]: DscoreApp: An user-friendly web application for computing the Implicit Association   Test D-score

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1600]
**Submitting author:** @OttaviaE (<a href="http://orcid.org/0000-0001-8552-568X">Ottavia M. Epifania</a>)
**Repository:** <a href="https://github.com/OttaviaE/DscoreApp" target ="_blank">https://github.com/OttaviaE/DscoreApp</a>
**Version:** v1.0.0
**Editor:** @alexhanna
**Reviewers:** @benmarwick, @tomfaulkenberry

**Author instructions**

Thanks for submitting your paper to JOSS @OttaviaE. **Currently, there isn't an JOSS editor assigned** to your paper.

@OttaviaE if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1600 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
Hi @OttaviaE, thanks for your submission to JOSS!

Unfortunately, we currently only support papers written in Markdown; our documentation has a good example that shows all the features supported: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

Can you please convert your current `paper.Rmd` to the format we support, and let us know when you have? Thanks!

**Comment by kyleniemeyer** [comment]
@alexhanna can you edit this submission? Thanks!

**Comment by alexhanna** [comment]
Sure.

**Comment by alexhanna** [comment]
@whedon assign @alexhanna as editor

**Comment by whedon** [comment]
OK, the editor is @alexhanna

**Comment by alexhanna** [comment]
@ottaviae Could you suggest two reviewers for this submission? Please look at the initial message in this issue for our list of reviewers.

**Comment by OttaviaE** [comment]
Hi @kyleniemeyer, 

I'm sorry, I've just pushed the md file on Github. 

Thanks!

**Comment by kyleniemeyer** [comment]
@OttaviaE no worries! But actually, I think the converted Markdown file is still not quite right. We do use the YAML header like what you had before, cite references from the `.bib` file, and support Markdown tables and figures.

I will try to do a quick pass through and fix it up for you.

**Comment by OttaviaE** [comment]
@alexhanna, I think @benmarwick and @masalmon might be appropriate reviewers.

thanks!

**Comment by OttaviaE** [comment]
@kyleniemeyer I might have uploaded the correct format this time, I'm truly sorry for the inconvenience!

**Comment by kyleniemeyer** [comment]
Let's give it a shot!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1600 with the following error: 

 ORCID looks to be the wrong length
/app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:123:in `block in check_orcids': Problem with ORCID (0000-0001-8552-568) for Ottavia M. Epifania (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:121:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:121:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:81:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
@OttaviaE looks like your ORCID is missing a digit (0000-0001-8552-568)

**Comment by OttaviaE** [comment]
@kyleniemeyer  This is quite odd because my ORCID ends with an "X"

**Comment by kyleniemeyer** [comment]
@OttaviaE ah sorry, I just meant that it should be 16 characters long, and is missing the final character. Can you fix it to be `0000-0001-8552-568X` ?

**Comment by OttaviaE** [comment]
@kyleniemeyer done! 

(Thanks for your patience)

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01600/joss.01600/10.21105.joss.01600.pdf)

**Comment by kyleniemeyer** [comment]
🎉 !

It looks like there are still some issues with the figures, which I should be able to fix quickly. One minute.

**Comment by kyleniemeyer** [comment]
@OttaviaE OK, please merge https://github.com/OttaviaE/DscoreApp/pull/1, that should do the trick.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01600/joss.01600/10.21105.joss.01600.pdf)

**Comment by OttaviaE** [comment]
@kyleniemeyer yay, look like it worked! Thank you so much!

**Comment by kyleniemeyer** [comment]
OK @alexhanna, all yours!

**Comment by labarba** [comment]
👋 @alexhanna — It looks like this submission is waiting for you to assign reviewers. Could you pop in and take a new look?

**Comment by alexhanna** [comment]
👋 @benmarwick and @sctyner, could you review this package?

**Comment by sctyner** [comment]
I decline. I just don't have the time right now. I may be more available next month.

**Comment by OttaviaE** [comment]
@alexhanna Hey! so what I should do now?

**Comment by benmarwick** [comment]
I reviewed this submission using the [guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and [checklist](https://joss.readthedocs.io/en/latest/review_checklist.html). Items needing further attention by the authors are marked with a 👀Disclaimer: I'm not a psychologist, don't have a strong understanding of what a D-score is, so my review does not evaluate the correctness of calculations performed by this app.

Looking at the [paper.pdf](https://github.com/openjournals/joss-papers/blob/joss.01600/joss.01600/10.21105.joss.01600.pdf), here's what I saw:

- [x] A list of the authors of the software
- [x] Author affiliations
- [ ] A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience -> 👀 I recommend the authors identify the research community that will find this useful, e.g. "...most commonly used measures in psychology for ..."
- [x] A clear statement of need that illustrates the purpose of the software
Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it
- [x] A list of key references including a link to the software archive

### Conflict of interest
- [x] As the reviewer I confirm that I have read the JOSS conflict of interest policy and that there are no conflicts of interest for me to review this work.

### Code of Conduct
- [x] I confirm that I read and will adhere to the JOSS code of conduct.

### General checks
- [x] Repository: Is the source code for this software available at the repository url?
- [x] License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?
- [ ] Version: Does the release version given match the GitHub release (v0.8)? -> 👀 I could not find version numbers, these need to be made easier to see
- [x] Authorship: Has the submitting author made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality
- [x] Installation: Does installation proceed as outlined in the documentation?
- [ ] Functionality: Have the functional claims of the software been confirmed? -> 👀 I had a problem running the app because of a absolute path in `server.R` for the example data. After I changed L22 to `dataset <- read.csv(here::here("raceAPP.csv"))` then the data could load in the shiny app and everything worked as expected.
- [x] Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation
- [x] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified? -> 👀 I didn't see these 
- [ ] Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support  -> 👀 I didn't see a CONTRIBUTING.md or similar in the app or on the repo.

### Software paper
- [x] Authors: Does the paper.md file include a list of authors with their affiliations?
- [x] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by OttaviaE** [comment]
Hey @benmarwick thank you for your review! I tried to solve the issues you highlighted: 
1.	“I recommend the authors identify the research community that will find this useful, e.g. "...most commonly used measures in psychology for ...". Done
2.	“I could not find version numbers, these need to be made easier to see”. I add the version number in the README.md file
3.	“I had a problem running the app because of a absolute path in `server.R` for the example data.”. Since the app is meant for being used online at the URL http://fisppa.psy.unipd.it/DscoreApp/, I added the instructions for changing the wd for the example dataset in the README.md file.
4.	“Automated tests”. You can find the tests for the app functioning here https://github.com/OttaviaE/DscoreApp/tree/master/tests plus a `running_test.R` script in the GitHub directory 
5.	“I didn't see a CONTRIBUTING.md or similar in the app or on the repo.” I added the CONTRIBUTING.md file to the repo. On the online version of the app at http://fisppa.psy.unipd.it/DscoreApp/ I left my personal email for reporting bugs/ask for support under the “Contacts” in the “Read Me First” panel. 

Hope it helps!

**Comment by arfon** [comment]
Thanks for your review here @benmarwick and your response @OttaviaE. I realize it might not be entirely clear but the actual JOSS review happens in a separate issue on GitHub that is set up by the editor (@alexhanna) once they have identified multiple reviewers.

I believe @alexhanna still needs to identify a second reviewer for this submission and will set up the main review issue at that point. 

@benmarwick - we can just copy over your review comments at that point :-)

**Comment by arfon** [comment]
@whedon add @benmarwick as reviewer

**Comment by whedon** [comment]
OK, @benmarwick is now a reviewer

**Comment by arfon** [comment]
@alexhanna - I think this paper is still in need of a second reviewer.

**Comment by OttaviaE** [comment]
Hey @alexhanna do I need to find myself another reviewer or will you take care of that?

**Comment by alexhanna** [comment]
If you could recommend one, that would be great.

**Comment by OttaviaE** [comment]
@alexhanna maybe @russellpierce might be a suitable reviewer

**Comment by russellpierce** [comment]
I'm sorry, I don't think I can provide good service as a reviewer on an IAT paper.

**Comment by OttaviaE** [comment]
@russellpierce it's not actually on the IAT itself, it's more focused on the score as it's usually computed according to Greenwald et al. (2003).

**Comment by OttaviaE** [comment]
@alexhanna Since @russellpierce is not suitable for this review, maybe @sctyner would like to do it

**Comment by alexhanna** [comment]
Hi @sctyner are you able to review this?

**Comment by alexhanna** [comment]
Hi -- @rmhogervorst, @tomfaulkenberry, @andytwoods -- can any of you serve as a second reviewer for this article?

**Comment by alexhanna** [comment]
@whedon add @tomfaulkenberry as reviewer

**Comment by whedon** [comment]
OK, @tomfaulkenberry is now a reviewer

**Comment by alexhanna** [comment]
@whedon start review
