### ISSUE TITLE
[REVIEW]: Gridap: An extensible Finite Element toolbox in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2520]
**Submitting author:** @fverdugo (<a href="http://orcid.org/0000-0003-3667-443X">Francesc Verdugo</a>)
**Repository:** <a href="https://github.com/gridap/Gridap.jl" target ="_blank">https://github.com/gridap/Gridap.jl</a>
**Version:** v0.13.4
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @PetrKryslUCSD, @TeroFrondelius, @KristofferC
**Archive:** <a href="https://doi.org/10.5281/zenodo.3999839" target="_blank">10.5281/zenodo.3999839</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4f3499aaf815c94db88feb96c8b7666c/status.svg)](https://joss.theoj.org/papers/4f3499aaf815c94db88feb96c8b7666c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4f3499aaf815c94db88feb96c8b7666c"><img src="https://joss.theoj.org/papers/4f3499aaf815c94db88feb96c8b7666c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4f3499aaf815c94db88feb96c8b7666c/status.svg)](https://joss.theoj.org/papers/4f3499aaf815c94db88feb96c8b7666c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/gridap/Gridap.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@PetrKryslUCSD, @TeroFrondelius, and @KristofferC, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/gridap/Gridap.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fverdugo) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/gridap/Gridap.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fverdugo) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/gridap/Gridap.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fverdugo) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @PetrKryslUCSD, @TeroFrondelius it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2520 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02520/joss.02520/10.21105.joss.02520.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@PetrKryslUCSD @TeroFrondelius this is where the review of the [paper](https://github.com/openjournals/joss-papers/blob/joss.02520/joss.02520/10.21105.joss.02520.pdf) and the [software](https://github.com/gridap/Gridap.jl) takes place. You each have a set of checkboxes at the top of this issue to guide you through the process. You can leave small comments here but for larger items we encourage you to open dedicated issues on the software project's repository and to link to them here. 

FYI See the above instructions :point_up: to turn off notifications from the other review issues. 

Let me know if you have any questions. 

Our review criteria: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @KristofferC as reviewer

**Comment by whedon** [comment]
OK, @KristofferC is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@KristofferC thanks for also helping with this review. See the instructions above for more information about the review process. Let me know if you have any questions.

**Comment by PetrKryslUCSD** [comment]
Filed three issues: https://github.com/gridap/Gridap.jl/issues/334, https://github.com/gridap/Gridap.jl/issues/335, https://github.com/gridap/Gridap.jl/issues/336.

**Comment by fverdugo** [comment]
I have created a new milestone

https://github.com/gridap/Gridap.jl/issues?q=is%3Aopen+is%3Aissue+milestone%3Ajoss_paper

to track the progress in addressing all the issues associated with this review.

You are welcome to use it, when opening a new issue in Gridap associated with this review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@PetrKryslUCSD, @TeroFrondelius, @KristofferC could you give a brief update on where this stands? It looks like @fverdugo resolved some of the issues pointed out. :point_up:, perhaps you can check those out. 

@TeroFrondelius, @KristofferC can you start working on those checkboxes? 

Thanks for all your help!

**Comment by TeroFrondelius** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02520/joss.02520/10.21105.joss.02520.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@KristofferC thanks for your help here. When can we expect your review contributions?

**Comment by KristofferC** [comment]
Hello again and sorry for the late replies. I will give my comments so they are available here within 24 hours. I hope that is OK.

**Comment by PetrKryslUCSD** [comment]
I note that the typesetting of the code is not resolved yet.

**Comment by TeroFrondelius** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02520/joss.02520/10.21105.joss.02520.pdf)

**Comment by TeroFrondelius** [comment]
> I have created a new milestone
> 
> https://github.com/gridap/Gridap.jl/issues?q=is%3Aopen+is%3Aissue+milestone%3Ajoss_paper
> 
> to track the progress in addressing all the issues associated with this review.
> 
> You are welcome to use it, when opening a new issue in Gridap associated with this review.

That's cool. However, I don't have suitable rights to assign milestones to the issues.

**Comment by fverdugo** [comment]
> That's cool. However, I don't have suitable rights to assign milestones to the issues.

Don't worry, I am doing it.

**Comment by KristofferC** [comment]
@Kevin-Mattheus-Moerman my invitation expired so I cannot check the boxes, I'll be doing it in this comment in the meantime:

---------------

Review checklist for @KristofferC
Conflict of interest

    I confirm that I have read the JOSS conflict of interest (COI) policy and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

Code of Conduct

    I confirm that I read and will adhere to the JOSS code of conduct.

General checks

Repository: Is the source code for this software available at the repository url?
License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?
Contribution and authorship: Has the submitting author (@fverdugo) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

    Substantial scholarly effort: Does this submission meet the scope eligibility described in the JOSS guidelines

Functionality

Installation: Does installation proceed as outlined in the documentation?
Functionality: Have the functional claims of the software been confirmed?

    Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

Documentation

A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

    Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Software paper

Summary: Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
State of the field: Do the authors describe how this software compares to other commonly-used packages?
Quality of writing: Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax?

**Comment by danielskatz** [comment]
@whedon re-invite @KristofferC as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@kristofferc please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by KristofferC** [comment]
With the exception of the typesetting of the code part (which confused me for a while), I think this paper/software is well written and I have checked all the boxes (and thus recommend accepting this paper).

**Comment by fverdugo** [comment]
@Kevin-Mattheus-Moerman Have you asked to the whedon technical staff if it is possible to hook these lines
```tex
\usepackage[utf8x]{inputenc}
\usepackage{textgreek}
```

Into your pandoc template so that the nabla operators are displayed correctly ?

**Comment by TeroFrondelius** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02520/joss.02520/10.21105.joss.02520.pdf)

**Comment by TeroFrondelius** [comment]
This is a well-written software/documentation/paper. I have raised a few minor issues which all have been addressed promptly by the authors. Therefore, I recommend accepting this paper. At the end, I want to thank you for the interesting experience of open/transparent peer-review.

**Comment by PetrKryslUCSD** [comment]
I am satisfied that the software and the paper meet the requirements for publication (with the exception of the symbols in the code, which are still not typeset correctly). I recommend publication, provided the typesetting errors can be resolved.

**Comment by fverdugo** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02520/joss.02520/10.21105.joss.02520.pdf)

**Comment by fverdugo** [comment]
@Kevin-Mattheus-Moerman I have added the code sniped as a figure. Now the code symbols are visualized correctly.

I would say that this fixes all issues.

**Comment by PetrKryslUCSD** [comment]
Looks good. I recommend publication as is.

**Comment by fverdugo** [comment]
Hi @Kevin-Mattheus-Moerman, 

the reviewers have given their approval several days ago.  Is something preventing the next steps towards the final publication?

**Comment by Kevin-Mattheus-Moerman** [comment]
@fverdugo apologies for the delay. This looks good and I will now proceed to process this paper for acceptance.

**Comment by Kevin-Mattheus-Moerman** [comment]
@fverdugo some final steps: 

- [ ] I've reviewed your paper and confirm it looks good. However can you remove this last sentence: 
`The source code for Gridap has been archived to Zenodo with the linked DOI 10.5281/zenodo.3934468.`, I ask this since the paper will have a link (top left) to the latest and more accurate archived version anyway. 

- [ ] This work is about to be processed for acceptance. Can you check the paper yourself once more and also check that the author names, affiliations, and the acknowledgements are accurate? 

- [ ] Can archive the latest version of the reviewed work on Zenodo and report back here with the archive DOI? Can you make sue the archive meta-data like the title and authors match that of the paper (you may need to edit information)? 

- [ ] The version is currently listed as `v0.12.0`, can you check if this is still accurate or if it needs to be altered?

**Comment by fverdugo** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02520/joss.02520/10.21105.joss.02520.pdf)

**Comment by fverdugo** [comment]
>  I've reviewed your paper and confirm it looks good. However can you remove this last sentence:
The source code for Gridap has been archived to Zenodo with the linked DOI 10.5281/zenodo.3934468., I ask this since the paper will have a link (top left) to the latest and more accurate archived version anyway.

I have removed the line (see the proof). **Note however, that the link to the archive (top left in the proof) is not working.** 

 > This work is about to be processed for acceptance. Can you check the paper yourself once more and also check that the author names, affiliations, and the acknowledgements are accurate?

It is ok from my side (except the broken link, which has to be fixed). @santiagobadia can you take your final look?


> Can you archive the latest version of the reviewed work on Zenodo and report back here with the archive DOI? Can you make sure the archive meta-data like the title and authors match that of the paper (you may need to edit information)?

I have archived the latest stable version of Gridap (v0.13.4)

  [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3999839.svg)](https://doi.org/10.5281/zenodo.3999839) 

The meta-data matches the one of the paper.

 > The version is currently listed as v0.12.0, can you check if this is still accurate or if it needs to be altered? (it should match the Zenodo archive version also)

v0.12.0 is out-of-date. The latest archived one is v0.13.4.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.3999839 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3999839" target="_blank">10.5281/zenodo.3999839</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set v0.13.4 as version

**Comment by whedon** [comment]
OK. v0.13.4 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2520 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02520/joss.02520/10.21105.joss.02520.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@fverdugo the link should work in the accepted paper form. You asked @santiagobadia to review the paper as well so I'll wait until I hear back from yourself or @santiagobadia if we can proceed with acceptance.

**Comment by santiagobadia** [comment]
Everything OK. @Kevin-Mattheus-Moerman you can proceed with acceptance.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2520 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s11831-017-9244-1 is OK
- 10.23998/rm.64224 is OK
- 10.21105/joss.00602 is OK
- 10.1137/15M1020575 is OK
- 10.5281/zenodo.3357100 is OK
- 10.1137/141000671 is OK
- 10.1145/1268776.1268779 is OK
- 10.1007/978-3-319-52462-7 is OK
- 10.1145/1644001.1644009 is OK
- 10.1145/1163641.1163644 is OK
- 10.1145/2998441 is OK
- 10.1016/j.cpc.2019.107059 is OK
- 10.1007/s11831-017-9244-1 is OK
- 10.5334/jors.151 is OK
- 10.5334/jors.182 is OK
- 10.1145/1731022.1731030 is OK
- 10.11588/ans.2015.100.20553 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1670

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1670, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@fverdugo @santiagobadia I'll process the final steps in the morning. In the meantime you can check the above PDF.

**Comment by santiagobadia** [comment]
@Kevin-Mattheus-Moerman everything OK

**Comment by fverdugo** [comment]
@Kevin-Mattheus-Moerman everything OK

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true from branch joss

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1298538586267099136) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1671
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02520](https://doi.org/10.21105/joss.02520)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by Kevin-Mattheus-Moerman** [comment]
@fverdugo @santiagobadia congratulations on getting this nice work published! It was a pleasure to edit. 

P.S. I have also personally started to explore this interesting software and am impressed by its speed/simplicity. It would be great if future work included the use of Julia based visualization, e.g. by using Makie for all meshing, boundary condition specification, and result visualizations.

**Comment by Kevin-Mattheus-Moerman** [comment]
@PetrKryslUCSD, @TeroFrondelius, @KristofferC thanks for reviewing this work!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02520/status.svg)](https://doi.org/10.21105/joss.02520)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02520">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02520/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02520/status.svg
   :target: https://doi.org/10.21105/joss.02520
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02520/status.svg)](https://doi.org/10.21105/joss.02520)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by santiagobadia** [comment]
Thanks @Kevin-Mattheus-Moerman for your work

> P.S. I have also personally started to explore this interesting software and am impressed by its speed/simplicity. It would be great if future work included the use of Julia based visualization, e.g. by using Makie for all meshing, boundary condition specification, and result visualizations.

Excellent!!!

Take a look at this repos wrt Makie + Gridap

https://github.com/gridap/GridapMakie.jl

@jw3126 is a new collaborator of the Gridap project that is doing an excellent job leading this dev
