### ISSUE TITLE
[REVIEW]: ChebTools: C++11 (and Python) tools for working with Chebyshev expansions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#569]
**Submitting author:** @ianhbell (<a href="http://orcid.org/0000-0003-1091-9080">Ian Bell</a>)
**Repository:** <a href="https://github.com/usnistgov/ChebTools" target ="_blank">https://github.com/usnistgov/ChebTools</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewer:** @drvinceknight
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1172036" target="_blank">10.5281/zenodo.1172036</a>

## Status

[![status](http://joss.theoj.org/papers/ad1978436659a414fac61ec0c40fe829/status.svg)](http://joss.theoj.org/papers/ad1978436659a414fac61ec0c40fe829)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ad1978436659a414fac61ec0c40fe829"><img src="http://joss.theoj.org/papers/ad1978436659a414fac61ec0c40fe829/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ad1978436659a414fac61ec0c40fe829/status.svg)](http://joss.theoj.org/papers/ad1978436659a414fac61ec0c40fe829)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/usnistgov/ChebTools" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@drvinceknight, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/usnistgov/ChebTools">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@ianhbell) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @drvinceknight it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #569 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     78      0 --:--:-- --:--:-- --:--:--    78
Error producing PDF.
! LaTeX Error: File `fancyvrb.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.153 \newcommand

Looks like we failed to compile the PDF

```

**Comment by labarba** [comment]
OK, @drvinceknight: here's where the action happens. If you've reviewed for JOSS before, you know the drill. If not, I'm here to answer your questions!

**Comment by labarba** [comment]
@ianhbell -- Your paper is not compiling. Can you check on that?

**Comment by ianhbell** [comment]
I don't think that is related to my paper.  I don't do anything too crazy, perhaps it is related to my Python code block?  I don't have any way of testing compilation on my side.  I asked several times about that but was never able to get a working build to the journal specs on my machine.  I think the whedon server needs to have the LaTeX package added.

**Comment by labarba** [comment]
@arfon : Can you help here? The paper is not compiling.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #569 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     67      0 --:--:-- --:--:-- --:--:--    67
Error producing PDF.
! LaTeX Error: File `fancyvrb.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.153 \newcommand

Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
@labarba @ianhbell - looks like our @whedon LaTeX environment doesn't include `fancyvrb` (which is probably associated with the code block). I've added it in https://github.com/openjournals/heroku-buildpack-tex/commit/5563891f668a8b7dd62fd67f740a79a5e80772d4 but this won't get deployed for a while.

For now will this copy of the paper work that I compiled locally? [10.21105.joss.00569.pdf](https://github.com/openjournals/joss-reviews/files/1706802/10.21105.joss.00569.pdf)

**Comment by ianhbell** [comment]
That local copy looks beautiful!

How about making a docker container with whedon inside?  That might be the cleanest packaging.  I can try to help with that if you are interested?

**Comment by drvinceknight** [comment]
> OK, @drvinceknight: here's where the action happens. If you've reviewed for JOSS before, you know the drill. If not, I'm here to answer your questions!

I haven't reviewed for JOSS before but everything looks pretty self explanatory (I'm just sat here thinking how great the whole system is!).

I'm aiming to complete this over next couple of days.

**Comment by drvinceknight** [comment]
## Installation

1. `python setup.py install` fails if `cmake` is not installed (on linux), could we add that to the `README.md` (`apt install cmake` solves this without a problem).
2. Once `cmake` is installed `python setup.py install` still fails, here's the tail of the output:
   
   ````
   -- Performing Test OpenMP_FLAG_DETECTED - Success
   -- Found OpenMP: -fopenmp  
   CMake Error at CMakeLists.txt:32 (add_subdirectory):
     The source directory
   
       /home/vince/Desktop/ChebTools/externals/pybind11
   
     does not contain a CMakeLists.txt file.
   
   
   CMake Error at CMakeLists.txt:33 (pybind11_add_module):
     Unknown CMake command "pybind11_add_module".
   
   
   -- Configuring incomplete, errors occurred!
   See also "/home/vince/Desktop/ChebTools/build/temp.linux-x86_64-3.5/CMakeFiles/CMakeOutput.log".
   Traceback (most recent call last):
     File "setup.py", line 70, in <module>
       zip_safe=False,
     File "/home/vince/anaconda3/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup
       return distutils.core.setup(**attrs)
     File "/home/vince/anaconda3/lib/python3.5/distutils/core.py", line 148, in setup
       dist.run_commands()
     File "/home/vince/anaconda3/lib/python3.5/distutils/dist.py", line 955, in run_commands
       self.run_command(cmd)
     File "/home/vince/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
       cmd_obj.run()
     File "/home/vince/anaconda3/lib/python3.5/site-packages/setuptools/command/develop.py", line 36, in run
       self.install_for_development()   
     File "/home/vince/anaconda3/lib/python3.5/site-packages/setuptools/command/develop.py", line 136, in install_for_development
       self.run_command('build_ext')
     File "/home/vince/anaconda3/lib/python3.5/distutils/cmd.py", line 313, in run_command
       self.distribution.run_command(command)
     File "/home/vince/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
       cmd_obj.run()
     File "setup.py", line 34, in run
       self.build_extension(ext)
     File "setup.py", line 58, in build_extension
       subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
     File "/home/vince/anaconda3/lib/python3.5/subprocess.py", line 581, in check_call
       raise CalledProcessError(retcode, cmd)
   subprocess.CalledProcessError: Command '['cmake', '/home/vince/Desktop/ChebTools', '   -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/vince/Desktop/ChebTools', '-
   DPYTHON_EXECUTABLE=/home/vince/anaconda3/bin/python', '-DCMAKE_BUILD_TYPE=Release']' 
   returned non-zero exit status 1
   ```
3. All the instructions in https://github.com/usnistgov/ChebTools#cmake-build work fine and following those running `python setup.py install` reports no error however there is still a problem when importing the library:

   ```
   Desktop: python
   Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
   [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
   Type "help", "copyright", "credits" or "license" for more information.
    >>> import ChebTools
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
   ImportError: /home/vince/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found 
   (required by /home/vince/Desktop/ChebTools/ChebTools.cpython-35m-x86_64-linux-gnu.so)
   >>> 
   ```

My suggestion would be to modify the install instructions to make the `cmake-build` instructions the standard way, currently I think "Install in one line from github" https://github.com/usnistgov/ChebTools#to-install-in-one-line-from-github is a bit misleading?

## Documentation

As far as I can see there's no simple example usage in the `README.md`. I know there is a binder link but also having a minimum example in the `README.md` is necessary. The small example that's in the paper would be fine.

There is also no "A statement of need" in the documentation (`README.md`), the statement of need in the paper is great.

## Community

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

This seems to be missing.

## Release version

@labarba I'm not entirely sure I follow this:

> Version: Does the release version given match the GitHub release (v1.0.0)?

As far as I can tell this software is "only" released on github. Is this requiring/expecting the software itself to be archived on a service like Zenodo?

---

I haven't been able to test any of the Functionality aspects, will do that once I've understood what I've missed with the installation. @ianhbell I hope this is helpful and please let me know if I've misunderstood anything.

**Comment by labarba** [comment]
@drvinceknight : The software will need to be archived on Zenodo or similar, and get a DOI. But we've relaxed the requirement to have that _before_ acceptance, because when the review elicits changes, this leads to a new release. We ask that authors deposit the accepted version.

**Comment by ianhbell** [comment]
@drvinceknight - the build problem you had was almost certainly because you didn't do a recursive git clone - I've been bitten by that innumerable times.  I updated the docs to try to address that issue and I tried to address your other concerns as well.

What do you think now: https://github.com/usnistgov/ChebTools ?  

Ready for any other review you care to offer.

**Comment by ianhbell** [comment]
And yes, I have minted a doi on zenodo already, but I'll remake the release when the review is complete.

**Comment by drvinceknight** [comment]
@ianhbell the docs look great! Thanks for those changes.

I'm still having issues installing on my system though:

```
Desktop: pip install git+git://github.com/usnistgov/ChebTools.git
Collecting git+git://github.com/usnistgov/ChebTools.git
  Cloning git://github.com/usnistgov/ChebTools.git to /tmp/pip-yimzocuc-build
Installing collected packages: ChebTools
  Running setup.py install for ChebTools ... done
Successfully installed ChebTools-1.0.0
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Desktop: python
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ChebTool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'ChebTool'
>>> import ChebTools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/vince/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/vince/anaconda3/lib/python3.5/site-packages/ChebTools.cpython-35m-x86_64-linux-gnu.so)

```

I went for the `pip install git+git://github.com/usnistgov/ChebTools.git` approach which succeeded but as you can see I still seem to have some issues with it finding some file.

**Comment by ianhbell** [comment]
Sorry I forgot to answer about that import error.  That's a bug in anaconda... : https://github.com/ContinuumIO/anaconda-issues/issues/483

The short answer is : delete the libstdc++ that it references, and it will then hook your system GLIBC and it should all work fine, though you *might* want to backup your libstdc++ before you do that :)

**Comment by drvinceknight** [comment]
Running `conda install libgcc` fixed it for me (is it worth including something about that in the README perhaps?).

**Comment by ianhbell** [comment]
Sure, I can do that

**Comment by drvinceknight** [comment]
Thanks for the changes @ianhbell! Nice piece of software and a nice paper :)

I have now ticked all boxes @labarba (except the one about the version but that all seems fine to me). Is there anything more formal I should do at this point? :)

**Comment by ianhbell** [comment]
Added to the README.

**Comment by labarba** [comment]
I take it your recommendation is to accept the submission, at this point, @drvinceknight ?

**Comment by drvinceknight** [comment]
> I take it your recommendation is to accept the submission, at this point, @drvinceknight ?

Yes, my recommendation is to accept the submission.

**Comment by labarba** [comment]
@ianhbell : Can you update the release, up the DOI version in Zenodo, and post the DOI right here, so we can link it to the article?

@arfon : This one is ready to publish.

**Comment by ianhbell** [comment]
All done!

DOI: 10.5281/zenodo.1172036

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1172036 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1172036" target="_blank">10.5281/zenodo.1172036</a> is the archive.

**Comment by arfon** [comment]
@drvinceknight - many thanks for your review here and to @labarba for editing this submission ✨ 

@ianhbell - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00569 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00569/status.svg)](https://doi.org/10.21105/joss.00569)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00569/status.svg)](https://doi.org/10.21105/joss.00569)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
